### PR TITLE
Nsa 2310 grafana

### PR DESCRIPTION
**Pull request by smneal**
- Add storage container template
- Add Grafana template
- Add MySQL firewall rule template
- Add Azure App Service Mount Script
- Update storage-account template
- Update app-service-linux template (used by the proxies)

### CODE REVIEW

**Comment by smneal** [comment]
> I dont understand this one. There seems to be duplicate templates in building blocks and shared folders. Linux app service as an example.
> 
> Is this branch for grafana work?

The branch is yes, but I thought I'd start creating some building blocks that weren't linked in with the bits in the shared folder. It made sense to use these with Grafana as starting point.

**Comment by OutKa5t** [comment]
Im still confused as to why we are separating the building blocks.

**Comment by smneal** [comment]
> Im still confused as to why we are separating the building blocks.

I didn't want to make changes to the existing templates and inadvertently break something so thought it best to start afresh.

**Comment by OutKa5t** [comment]
Getting this aligned back in is going to be a sizeable task now. I suggest you make the Grafana building blocks a separate folder and have '2' copies of building blocks e.g.

/shared/buildingblock.json
/grafana/buildingblock.json

**Pull request merged**
